# Mod
mod_id = gravelminer
mod_name = Gravel Miner
mod_author = BlayTheNinth
credits = BlayTheNinth
description=Automatically (insta-)mines falling gravel blocks that get in your way while mining.
version = "26.1.0"
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/mc/gravelminer
sources=https://github.com/TwelveIterations/GravelMiner
issues=https://github.com/TwelveIterations/GravelMiner/issues
discord = https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved

# Publishing
curseforge_project_id = 244759
curseforge_environments = Client,Server
modrinth_project_id = iAzrhsju
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 21
neoforge_snapshot_url =
include_fabric=true
include_neoforge=true
include_forge=true

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
