name: Update Version Branch

on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        description: 'Minecraft Version (default: this)'
        required: false
        type: string

jobs:
  call-update-version-branch:
    uses: TwelveIterations/PortingScripts/.github/workflows/update-version-branch.yml@v1
    with:
      minecraft_version: ${{ inputs.minecraft_version || github.ref_name }}
      environment: Automations
    secrets:
      AUTOMATIONS_APP_ID: ${{ vars.AUTOMATIONS_APP_ID }}
      AUTOMATIONS_PRIVATE_KEY: ${{ secrets.AUTOMATIONS_PRIVATE_KEY }}
